apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.AppName }}-ingress
  namespace: {{ .Values.NameSpace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.HostName }}
    secretName: {{ .Values.AppName }}-tls
  rules:
  - host: {{ .Values.HostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.AppName }}-service
            port:
              number: 80